# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build mariget-auth`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t mariget-auth`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system mariget-auth && \
          adduser --system -G mariget-auth mariget-auth

COPY dist/mariget-auth mariget-auth/
RUN chown -R mariget-auth:mariget-auth .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix mariget-auth --omit=dev -f install

CMD [ "node", "mariget-auth" ]
